### ISSUE TITLE
Mutant selection strategies and random mutant selection strategies are not the same

### ISSUE THREAD

**Issue by DurieuxPol** [pharo-contributions/mutalk#105]
I figured out when writing the wiki that a few months ago we renamed mutant _generation_ strategies as mutant _selection_  strategies while we probably shouldn't have.
These strategies are about selecting, but selecting the methods to be mutated, not the mutants themselves (like, generating mutants from all methods or only covered methods).
On the other hand random mutant selection strategies are indeed about selecting mutants in a specific way.

So I think we should re-rename mutant selection strategies as mutant generation strategies, and make a clear difference between them and random mutant selection strategies.

**Comment by guillep** [comment]
Ok! Would you like proposing something that is both understandable and easy to use? ^^
