### ISSUE TITLE
TestTookTooMuchTime exception stops the analysis

### ISSUE THREAD

**Issue by PalumboN** [pharo-contributions/mutalk#94]
I was running the mutations and a debugger opened due to a TestTookTooMuchTime exception because of an infinite loop (consequence of the mutation).

This exception should count as any exception, failing the test and killing the mutant. 
And, also important, to not stop the analysis.

**Comment by DurieuxPol** [comment]
There are tests in MuTalk that normally handle infinite loops. Maybe you changed something in the API of unit tests and the excepetion is not handled anymore.

**Comment by PalumboN** [comment]
How is it handled? It was an infinite recursion really.

**Comment by guillep** [comment]
Yes but SUnit already manages that, and we depend on that support.
What I was discussing with @DurieuxPol is that maybe some tests in the VM redefine `#runCaseManaged:` and probably workaround the time out detection support (which in turn breaks mutalk)

**Comment by DurieuxPol** [comment]
It is Pharo which handles it. What I meant is that there are tests in MuTalk where the analysis generates infinite loops (for example `MTAnalysisTest>>#testExecutingInfiniteLoopAnalysis`), but the tests checks if the mutant is killed.
So I don't think mutalk is the problem here.
